### ISSUE TITLE
Use of inline classes does not play well with iOS

### ISSUE THREAD

**Issue by dalewking** [korlibs/klock#108]
It was nice to use inline classes for some of the types, but unfortunately the Swift interoperability is greatly hampered by this. For example, a function that returns a Date or a DateTime when translated to Swift it simply becomes int32_t and the Date and DateTime classes are not accessible at all from Swift. This makes it extremely to write iOS apps dealing with dates. While it would be nice to be able to write all code in Kotlin without resorting to Swift, the fact that you can't export a UIViewController class to IOS makes that unrealistic

**Comment by soywiz** [comment]
The idea of doing this is because I'm using this library in projects where being as allocation-free as possible is pretty critical (games). Unfortunately Java unlike .NET doesn't support value types until Project Valhalla is out. Kotlin/Native as far as I'm concerned is not optimizing small immutable types as values types either. That's the same reasong I'm using Double types instead of Long so JS doesn't require allocations either. There are some tricks like object pooling, or threadlocals to be able to pass complex value to upper functions without allocating, but not implemented by Kotlin either due to complexity which makes sense.

I'm not pretty sure about a good solution. I could create two versions of the library, one providing inline classes, the other providing data classes. Kotlin/Native could also expose inline functions to swift as structs and do casting as required, no allocations either, but nicer to swift.

Summarizing:
* From my side I can only see the option of publishing two variants of the library (if you are aware of other solutions, please let me know)
* From the Kotlin side we could propose that they consider exposing inline types as structs and perform casting automatically starting with 1.4

What do you think?

**Comment by lamba92** [comment]
Also inline classes makes the Kotlinx serialization compiler plugin crash. 

I believe publishing two versions is the best solution.

**Comment by dalewking** [comment]
> Kotlin/Native could also expose inline functions to swift as structs and do casting as required, no allocations either, but nicer to swift.

Would be nice, but unfortunately is not the case. As noted [here](https://kotlinlang.org/docs/reference/native/objc_interop.html#unsupported):

> Currently, following features are not properly exposed in generated framework headers:
> 
> - inline classes (arguments are mapped as either underlying primitive type or id)

> From the Kotlin side we could propose that they consider exposing inline types as structs and perform casting automatically starting with 1.4

Apparently they will actually be [introducing their own date time classes in 1.4](https://blog.jetbrains.com/kotlin/2019/12/what-to-expect-in-kotlin-1-4-and-beyond/):

> The support for dates is really needed in the multiplatform world, and this is what we are working on: experimental Durations have been already added to stdlib, and DateTime support is under way.

**Comment by soywiz** [comment]
What I said was to propose doing that to the K/N team. Right now indeed it is not the case. 

> Some features of Kotlin programming language are not **yet** mapped into respective features of Objective-C or Swift. Currently, following features are not properly exposed in generated framework headers:

Yeah I'm aware of them to include date and time classes. Please read this one: https://github.com/korlibs/klock/issues/79

So the question is: would it help you at this point to expose a variant of the library without inline classes? Obviously all the dependencies using klock should use the same variant.

Right now, for passing dates you can use `DateTimeTz` that is not inline. And if you need another one, I can create a non-inline wrapper so you can use both and use the wrapper version to interop with swift.

**Comment by dalewking** [comment]
> So the question is: would it help you at this point to expose a variant of the library without inline classes? 

Unfortunately I am in the middle of implementing a page that is all about dates and am having to work around it. So unless it is available like this week I will already have it worked around.

What I am ending up doing is using extension methods in my iOS Kotlin code that wraps the existing methods to e.g. take year, month, day parameters instead of a Date and similar tactics.

**Comment by soywiz** [comment]
I have decided to not publish separate artifacts. I have created a wrapped package with all the inline classes prefixed with `W` (Wrapped). This should play nice with interoperability and serialization, and you can wrap with `.wrapped` and unwrap with `.value` at any time. Going to release this so you can use it in the case you still want this.
I have marked it as experimental warning for now in the case I have to change something after people try this out.

**Comment by soywiz** [comment]
Once the deploy is completed you can find this stuff in `1.11.0`:
https://github.com/korlibs/klock/commit/088119e824fedc11172e4a7afabe4376ae0f1059

**Comment by RomeuG** [comment]
Am I interpreting this issue the wrong way, or should WDateTime be translated to a DateTime in Swift?
Because what is happening is that WDateTime is still being translated to Double on Swift.

Should this be still happening after `1.11.0` ?
