### ISSUE TITLE
Wrong value while creating from unix.

### ISSUE THREAD

**Issue by icarumbas** [korlibs/klock#124]
val time: Long = 1593408524 // GMT: Monday, 29 June 2020 г., 5:28:44
val date = DateTime.fromUnix(time)
print(date) // Mon, 19 Jan 1970 10:36:48 UTC

**Comment by soywiz** [comment]
The unix timestamp you should provide should be in milliseconds (like on JavaScript). The one you are providing is in seconds (like in C or PHP), and that's why you are getting the wrong value. Instead of `1593408524` try with `1593408524000`.

The documentation of the method doesn't state that, so I'm setting the documentation label to fix that.

Thanks for reporting!
