### ISSUE TITLE
startOfDay returning incorrect value?

### ISSUE THREAD

**Issue by webfrea-k** [korlibs/klock#132]
I live in a UTC + 2 timezone.
When calling `DateTime.now().startOfDay` I get:
_Fri, 24 Jul 2020 00:00:00 UTC_
Shouldn't the call to `DateTime.now().startOfDay.local` return:
_Thu, 23 Jul 2020 22:00:00 GMT+0200_?
It currently returns:
_Fri, 24 Jul 2020 02:00:00 GMT+0200_

**Comment by SerVB** [comment]
@webfrea-k @soywiz 

I think it shouldn't return 2200. When you have midnight at UTC, you have 2am at GMT+2 (the night just comes earlier to GMT+2 because it's closer to the east 😅).

I've also checked this at <https://www.thetimezoneconverter.com/>:

![image](https://user-images.githubusercontent.com/20105593/114763615-aaf24e00-9d6b-11eb-97c4-9638e2bcff53.png)

Finally, this is not related to `startOfDay`, for me even strict dates work the same way:

```kotlin
val a = DateTime(2021, 4, 14)
val b = a.local

println(a)  // Wed, 14 Apr 2021 00:00:00 UTC
println(b)  // Wed, 14 Apr 2021 03:00:00 GMT+0300
```

So I guess this issue can be closed.

**Comment by webfrea-k** [comment]
Looks correct. I don't remember the case I was faced with back when I opened the issue, but the above makes sense @SerVB . Closing the issue.
