### ISSUE TITLE
Cannot find symbol when using library from Java

### ISSUE THREAD

**Issue by weliem** [korlibs/klock#155]
I am on Kotlin 1.4.10 and 2.0.0-alpha.

When I try to access properties of DateTimeTz I get an error.

`final double nowOffsetInMillis = DateTimeTz.Companion.nowLocal().getOffset();`

But then the compiler complains:

**error: cannot find symbol
        final double nowOffsetInMillis = DateTimeTz.Companion.nowLocal().getOffset();
                                                                        ^
  symbol:   method getOffset()
  location: class DateTimeTz**

It basically happens on any property, not only 'offset'

Any ideas?

**Comment by weliem** [comment]
Also tried 2.0.0-rc2 but the issue is still there.

**Comment by weliem** [comment]
Did some more experimentation.....getMinutes() works and any other that returns a basic type like Int work. But the ones that returns some other com.soywiz.klock class don't work

**Comment by soywiz** [comment]
@weliem Klock is not intended to be consumed from Java. The main problem here is that we are using `inline classes` that is not yet available on Java until they implement value types with [Valhalla](https://openjdk.java.net/projects/valhalla/).
Kotlin creates a special mangled names for functions using inlined types that probably won't be callable from Java. What Kotlin does is to mangle the function name + instead of receiving/returning for example TimeSpan, it receives/returns a Double, and the inline class functions are static.
This makes consuming the API from Java hard, or directly impossible. Once Java supports Valhalla, it is likely that Kotlin supports generating code using that stuff without having to mangling function names and stuff, and you will be able to consume it from modern Java versions directly, but for now, it is not possible.

**Comment by weliem** [comment]
We choose Kotlin for it's interoperability with Java and other platforms. We have been using Klock successfully for the last year and calling Klock from Java has never been a problem. But now that we are upgrading from 1.8.3 to 2.0.0, our code is broken. So did something change in Klock? Did older versions not use inline classes?

Anyway, perhaps I can write some extentions to fix the interoperability issues....

**Comment by soywiz** [comment]
I was not aware that some people was using it with Java, and directly assumed it was not possible. Inline classes are experimental, so I think that's something unreliable at this point. You could check the exported class methods on both versions of the library, maybe the signature change because inline classes are experimental.
I'd suggest you to stick to 1.8.3 for now. On Kotlin new compiled versions are needed because Kotlin/Native doesn't have binary compatibility of the libraries, but with the JVM you should be safe to stick with older versions.

**Comment by weliem** [comment]
I think our use case is very common: we have a library written in Kotlin Multi Platform which we use in our iOS, Android, and JVM applications. We use Klock in our library and it is also used in the external interface of the library. Hence interoperability with Java and Swift is essential...

Will try to find a workaround for now, but we would greatly appreciate it if future versions of your library would have improved interoperability.

**Comment by soywiz** [comment]
I'll investigate if we can do something regarding to binary compatibility, but if Kotlin started to use synthetic mangled methods with different signature on 1.4 because inline classes are experimental and there are no guarantees for them, I'm not sure if we could do anything. In any case, this library is opensource and public domain, if you have workarounds you want to include here, just make a PR with your proposals 👍
