### ISSUE TITLE
Format DateTimeTz

### ISSUE THREAD

**Issue by BulatMukhutdinov** [korlibs/klock#158]
I have DateTimeTz with correct TimeZone but when I am formatting it 
```
val timeFormat = DateFormat("hh:mm")
val time = dateTimeTz.format(timeFormat)
```
I am getting time in UTC without adjected time zone

**Comment by soywiz** [comment]
Can you provide a failing test case like the ones in this file:
https://github.com/korlibs/klock/blob/9bdb793f9869263060c72e83465f64ff5357e167/klock/src/commonTest/kotlin/com/soywiz/klock/TimeFormatTest.kt#L6

reproducing your issue?

An specific input, with an expected output and an associated `assertEquals`

**Comment by BulatMukhutdinov** [comment]
My time zone is GMT+0300. ```date``` determines the correct time zone but formatting returns "11:03" instead of "14:03" and test fails
```
    @Test
    fun testFormatTz(){
        val now = 1611658981L // 26/01/2021 @ 11:03am (UTC)

        val timeFormat = DateFormat("hh:mm")
        val date = DateTimeTz.fromUnixLocal(now * 1000) // timezone GMT+0300

        val formatted = date.format(timeFormat)

        assertEquals("14:03", formatted)
    }
```

**Comment by soywiz** [comment]
Thanks. I guess that should do.

Might be a good idea to be able to provide a custom `TimeZone` when construting the `DateTimeTz` for the tests to override the local one.

**Comment by Caps-Looking** [comment]
The problem is: the function `fromUnixLocal` is adding the timezone in the end, but is not adjusting the hours to the local timezone.
When we call the `format` function, the time is in timezone 0, and not local, even with GMT+0300 in the end.

```
    @Test
    fun testFormatTz(){
        val now = 1611658981L // 26/01/2021 @ 11:03am (UTC)

        val timeFormat = DateFormat("hh:mm z")
        val date = DateTimeTz.fromUnixLocal(now * 1000) // timezone GMT+0300

        val formatted = date.format(timeFormat) // Formating as: 11:03 GMT+0300

        assertEquals("14:03 GMT+0300", formatted)
    }
```

I suggest create a `fromUnix` function to apply the local timezone offset, like this:
```
        fun fromUnix(unix: Long): DateTimeTz {
            val unixDateTime = DateTime(unix)
            return utc(unixDateTime, TimezoneOffset.local(unixDateTime))
        }
```

So, when you call `fromUnix` and `format`, the time applied will be local:
```
    @Test
    fun testFormatTz(){
        val now = 1611658981L // 26/01/2021 @ 11:03am (UTC)

        val timeFormat = DateFormat("HH:mm z")
        val date = DateTimeTz.fromUnix(now * 1000) // timezone GMT+0300

        val formatted = date.format(timeFormat) // Formating as: 14:03 GMT+0300

        assertEquals("14:03 GMT+0300", formatted)
    }
```

If it makes sense, the code is already implemented, so I can open the PR.

**Comment by soywiz** [comment]
Feel free to open a PR 👍

**Comment by Caps-Looking** [comment]
@soywiz do you have any suggestions of how to mock the timezone? The code is ready, but IDK how to mock timezone for unit test, since there isn't any mock lib.

**Comment by soywiz** [comment]
Reflective/runtime-based approaches required for proper mocking won't work on Kotlin common without compiler plugins, so I have been very primitive with testing.

It seems that in Klock I decided to test things relying on specific timing functionality on the JVM without a mocking library, assuming that the code would work in other targets:

https://github.com/korlibs/klock/blob/a7a4908e8bb6847ae69d53e8e1f9d072a8054bae/klock/src/jvmMain/kotlin/com/soywiz/klock/internal/KlockInternal.kt#L17

Maybe a future version could make that functionality available to all the targets for mocking in tests and maybe per thread so tests could run concurrently.

For now, create the test in the JVM target. And please, since I'm synchronizing from next to korlibs manually from time to time, open the PR in the korge-next repository: https://github.com/korlibs/korge-next
