### ISSUE TITLE
add infix to functions?

### ISSUE THREAD

**Issue by tieskedh** [korlibs/klock#162]
Functions like `Month.withYear` and `Year.withMonth` could be infix-functions.
Maybe it's an idea to search for functions like this and add te infix-modifier?

**Comment by soywiz** [comment]
Thanks for your suggestion!

Right now in korlibs we are only using infix functions for operator-like functions like `umod` or other operators in DSLs to generate trees like (for example generating shaders, or query expressions), and they tend to be single words like AND, OR, shl, shr, etc.. I think the Kotlin standard library is following the same criteria.

The problem I see with infix is that it is hard to determine which functions with one receiver and one parameter should be infix or not, and we could question that on a lot of functions and that could be problematic.
From my perspective Infix functions have the drawback that sometimes it is not clear the evaluation order, and you still have to provide a parenthesis on the whole subexpression to state that. With long expressions, know what is a function/operator and what a local or property might be difficult to determine.
This kind of infix stuff was typically used on Scala, but I think it is not that used on Kotlin. In Scala there is this explanation on the controversial part of the infix: https://docs.scala-lang.org/style/method-invocation.html#arity-1-infix-notation
In addition to operators, Scala recommendation also use it with higher order functions, which it is not the case for the Kotlin standard library as far as I'm concerned.

I believe there is no warning for using an infix function as a normal method, so could work without breaking code or forcing other people to use that style, so I'm not totally against it and it is something that could be considered, but I would like to know why do you think it is better to write `Year(2000) withMonth Month.September` instead of `Year(2000).withMonth(Month.September)`, or just `YearMonth(2000, Month.September)`? Do you have samples on other libraries that are doing this and they argued its usage? Is it a matter of taste?

Since you suggested it, I'm interested in your thoughts on this matter to have a wider perspective

**Comment by tieskedh** [comment]
You've a good reason why not to include it!
I've not run into these issues you described yet.

The request is because of **personal taste**:
I like to split up chains and give the intermediate steps also a descriptive name.
This way the code becomes less dense and more easy to read.
(Just read almost everything from front to back, from top to bottom)
Infix functions would help by removing unneccesary characters.
I therefor like to add the infix keyword to functions that take only two parameters if it constructs something.

When you want to create some kind of algorithm (being expressive by showing the pure calculation), your way does make a lot more sense.

Thx for the detailed answer!
