### ISSUE TITLE
Update up to 1.6.0?

### ISSUE THREAD

**Issue by InsanusMokrassar** [korlibs/klock#180]
Is there some hope to see update up to kotlin 1.6.0?

**Comment by soywiz** [comment]
What do you mean? Doesn't latest version work for you in Kotlin 1.6.0?

**Comment by InsanusMokrassar** [comment]
I would be more sure that everything is alright in case when all dependencies have been built with kotlin 1.6.0 support :)

**Comment by soywiz** [comment]
Sure. Next version will be compiled against 1.6.0. It will be released sometime this December.

In addition to that, I believe Kotlin/Native started to support using libraries compiled for older versions a few versions ago. Due to a mistake latests versions were being compiled in 1.5.31, but we used 1.6.0-RC for generating final binaries, and seemed to work fine in all targets.

But as said, if you feel more confident with a 1.6.0 compiled version, one will be released later this month.

**Comment by InsanusMokrassar** [comment]
Thanks :)
