### ISSUE TITLE
Adding support to iosSimulatorArm64 architecture

### ISSUE THREAD

**Issue by hugolefrancois** [korlibs/klock#182]
Updating easyPluginVersion to version 0.17 will do the job.

**Comment by soywiz** [comment]
Supported in https://github.com/korlibs/korge-next/releases/tag/v2.4.9

**Comment by soywiz** [comment]
@juliankotrba It is correct: https://repo.maven.apache.org/maven2/com/soywiz/korlibs/klock/klock/2.4.9/

korge-next repo publishes all the artifacts to the https://repo.maven.apache.org/maven2/com/soywiz/korlibs/ package.
I know the name of the repo is misleading. It should be `korlibs-next` instead. Since it includes all the korlibs libraries in a single mono repo, and each one is published to the right package

**Comment by juliankotrba** [comment]
@soywiz you are right, I just looked at the GitHub releases.. Sorry, my bad!
Anyway, thanks for the clarification! 🙂
