### ISSUE TITLE
DateFormat with Japanese String is not correct

### ISSUE THREAD

**Issue by irgaly** [korlibs/klock#33]
At klock version 1.1.1, this code is not working properly.

```
val output = DateFormat("yyyy年MM月dd日").format(DateTime(2019, 4, 12))
```

The result, output is `yyyy年MM月dd日`.

Expected result is `2019年04月12日`.

**Comment by irgaly** [comment]
Sorry, I found this code https://github.com/korlibs/klock/blob/master/klock-locale/src/commonMain/kotlin/com/soywiz/klock/locale/ja.kt

This code works fine.

```
val output = DateFormat("yyyy'年'MM'月'dd'日").format(DateTime(2019, 4, 12))
```

output is `2019年04月12日`

Is this means a single quote as separator?

**Comment by soywiz** [comment]
Yes, right now it works like that: the single quote is used for literals. But I believe it is not required in java, and it is just required for characters that would cause problems, so I will check.

Will you need a mode to use kanji numbers in dates? `二〇一九年〇四月一二日` or the fixed-width unicode numbers: `２０１９年０４月１２日`

I guess this could apply to both japanese and chinese. I didn't add them because I was not fully sure, but I guess they would display better on japanese and chinese sites since the rest of the characters have already a fixed width.

**Comment by irgaly** [comment]
> 二〇一九年〇四月一二日

It is very rare situation. I have not seen this Kanji format in Web Services or Mobile Apps. It is used for literary or novel books. So I hove no trouble with no Kanji format support.

>  fixed-width unicode numbers: ２０１９年０４月１２日

Fixed-width date is sometimes used in Japanese sentences. It is used for beauty for display, but I think a displaying beautiful is a scope of font system.  I'm enough to use this code `DateFormat(...).format(date).toFullWidthNumber()` (toFullWidthNumber is such my extension that convert numbers to full width number).


This two format situations are the corner cases that someone has needed. I think it is no need to support that cases in default JapaneseKlockLocale, but I'm happy if I can support that situations with my custom Locale class.

**Comment by glenlsl** [comment]
The same is true with DateFormat("yyyyMMdd")
